### ISSUE TITLE
all multilanguage fields are displayed, not only the selected

### ISSUE THREAD

**Issue by tiefenb** [justb3a/processwire-imageextra#34]
<img width="1333" alt="bildschirmfoto 2018-03-09 um 20 36 10" src="https://user-images.githubusercontent.com/488163/37226274-b33cb58c-23d9-11e8-892e-e341d54d03a4.png">

This happens in PW 3.0.95 with new AdminThemeUIKit

**Comment by tiefenb** [comment]
I made some workaround by adding a custom css to my admin theme:

`/*

  fix for broken ImageExtra Fields Language CSS

*/
.Inputfields .LanguageSupport {
    display: none;
}

.Inputfields .LanguageSupport.LanguageSupportCurrent {
    display: block;
}

.InputfieldImageEdit__additional > div {
  margin: 20px 0;
}`

**Comment by julianwinkel** [comment]
A small optimization. otherwise the pagename fields in settings are hidden.

```css
.Inputfields .uk-tab ~ .LanguageSupport {
	display: none;
}

.Inputfields .uk-tab ~ .LanguageSupport.LanguageSupportCurrent {
	display: block;
}

.InputfieldImageEdit__additional > div {
	margin: 20px 0;
}
```
